title: estrela.me * blog
email: rsaestrela@gmail.com
description: "@rsaestrela raul estrela personal blog"
baseurl: /blog
url: "https://estrela.me"
markdown: kramdown
exclude: [vendor]
google_analytics: "UA-180685972-1"